### PR TITLE
Modified Encode and Decode functions

### PR DESCRIPTION
**Pull request by alwin48**

### CODE REVIEW

**Review by VipinVIP — CHANGES_REQUESTED** [review]
Just viewed the changes, . Also you can ask the review of @AnandBaburajan  also, so that he will be notified too 😇

**Review by VipinVIP — APPROVED** [review]

**Comment by anandbaburajan** [comment]
> Just viewed the changes, . Also you can ask the review of @AnandBaburajan also, so that he will be notified too

Yes, it's good if the tests were updated too. If CI/CD was setup here, you'd be notified of the failing tests and you'd have had to fix them before merging the PR :D Also, a description of what was updated is always helpful. Also, please remember to create new branches for new PRs :)

**Comment by VipinVIP** [comment]
> If CI/CD was setup here, you'd be notified of the failing tests and you'd have had to fix them before merging the PR

@alwin48  have looked into CircleCI and told me that it worked for him. But he said that He need the permission from org (i dont remember correctly) or something to Integrate it into this repo. I'll  let you know after knowing in much detail.

**Comment by VipinVIP** [comment]
@AnandBaburajan  So  I have to tell him to re-submit the PR after modifying the test right ?

**Comment by anandbaburajan** [comment]
> So I have to tell him to re-submit the PR after modifying the test right ?

Yep

> need the permission from org

Let me know what I need to do for the integration part

**Comment by anandbaburajan** [comment]
@alwin48 The changes look good! I'm merging this. I've also approved access for CircleCI. So I guess next PR onwards, the test results would be shown right? I think you can test that with by opening a PR for a test for the case with empty string or for #16. 
I forgot to mention, please rename `TestForboth.test.js` to `testEncodeDecode.js` next time

**Pull request merged**
