### PR TITLE
Polish up

### PR DESCRIPTION
**Pull request by VipinVIP**
Just as said, corrected  the file naming and added the CircleCI badge

### CODE REVIEW

**Comment by anandbaburajan** [comment]
Nice! I was actually looking forward to see CircleCI's checks here, on the PR like I said earlier:

> So I guess next PR onwards, the test results would be shown right? I think you can test that with by opening a PR for a test for the case with empty string or for #16.

So is something more to be done at CircleCI to test this PR's branch and show checks here?

**Comment by VipinVIP** [comment]
> Nice! I was actually looking forward to see CircleCI's checks here, on the PR like I said earlier:
> 
> > So I guess next PR onwards, the test results would be shown right? I think you can test that with by opening a PR for a test for the case with empty string or for #16.
> 
> So is something more to be done at CircleCI to test this PR's branch and show checks here?

I dont know really .. Maybe they run tests after Merging PR ? 

Have you used CircleCI before ? like do you know anyone who can help 😕

**Comment by anandbaburajan** [comment]
> Maybe they run tests after Merging PR ?

I don't think so because tests are supposed to be run before PRs are merged

> Have you used CircleCI before ? like do you know anyone who can help

Unfortunately no, but I think @alwin48 can take a look?

**Comment by VipinVIP** [comment]
> > Have you used CircleCI before ? like do you know anyone who can help
> 
> Unfortunately no, but I think @alwin48 can take a look?

I have already talked to him , and he too dont know well... But well.. we'll search and find 😇

**Comment by VipinVIP** [comment]
Finally ... everything worked 🥳 
I had to turn on a setting in circleCI to run test on all PR from forked repos 
image
Plus I copied a basic config from one of their tutorial docs 😅 , and had to update node version when the test failed

**Comment by anandbaburajan** [comment]
That's great! Congratulations to you both on completing OpenHack '20 successfully! Merging!

**Pull request merged**
